### PR TITLE
adding "author" and "container-author" variables

### PR DESCRIPTION
**Pull request by Elbar914**
Adding "author" and "container-author" variables to "chapter" source type. 

Examples are located here: https://www.legalbluebook.com/Public/QuickStyleGuide.aspx

• AIDS and the Law (Harlon L. Dalton et al. eds., 1987).
• Adrienne Rich, Transcendental Etude, in The Fact of a Doorframe 264, 267–68 (1984).

### CODE REVIEW

**Comment by Elbar914** [comment]
@iCreateJB can you take a look and merge if ok?

**Comment by Elbar914** [comment]
@iCreateJB can you take a look at this on Monday?

**Comment by btucker** [comment]
@iCreateJB @Elbar914 is this still relevant?

**Comment by Elbar914** [comment]
@btucker feel free to close

**Comment by illume** [comment]
unwatch, unwatch, unwatch. ( https://github.com/watching ) meow.

**Pull request closed without merging**
